const brandList = [
  {
    name: 'Spectra Premium',
    url: 'spectra-premium',
    imgsrc: 'assets/images/Brands/Spectra.png',
  },
  {
    name: 'A1 Cardone',
    url: 'a1-cardone',
    imgsrc: 'assets/images/Brands/AICardone.png',
  },
  {
    name: 'Intermotor',
    url: 'intermotor',
    imgsrc: 'assets/images/Brands/Intermotor.png',
  },
  { name: 'Dorman', url: 'dorman', imgsrc: 'assets/images/Brands/Dorman.png' },
  {
    name: 'StopTech',
    url: 'stoptech',
    imgsrc: 'assets/images/Brands/StopTech.png',
  },
  {
    name: 'Standard Ignition',
    url: 'standard-ignition',
    imgsrc: 'assets/images/Brands/Standard.png',
  },
  { name: 'Brembo', url: 'brembo', imgsrc: 'assets/images/Brands/Brembo.png' },
  {
    name: 'QuickSteer',
    url: 'quicksteer',
    imgsrc: 'assets/images/Brands/Quicksteer.png',
  },
  {
    name: 'TechSmart',
    url: 'techsmart',
    imgsrc: 'assets/images/Brands/Techsmart.png',
  },
  {
    name: 'Autolite',
    url: 'autolite',
    imgsrc: 'assets/images/Brands/Autolite.png',
  },
  {
    name: 'Bilstein',
    url: 'bilstein',
    imgsrc: 'assets/images/Brands/Bilstein.png',
  },
  { name: 'ADVICS', url: 'advics', imgsrc: 'assets/images/Brands/Advics.png' },
  { name: 'FCS Auto Parts', url: 'fcs-auto-parts' },
  { name: 'Arnott Industries', url: 'arnott-industries' },
  { name: 'Anchor', url: 'anchor' },
  { name: 'Moog', url: 'moog' },
  { name: 'Akebono EURO', url: 'akebono-euro' },
  { name: 'Drive Rite', url: 'drive-rite' },
  { name: 'Timken', url: 'timken' },
  { name: 'Dorman - TECHoice', url: 'dorman-techoice' },
  { name: 'MPA', url: 'mpa' },
  { name: 'Dorman - HD Solutions', url: 'dorman-hd-solutions' },
  { name: 'LuK', url: 'luk' },
  { name: 'Airtex Water Pumps', url: 'airtex-water-pumps' },
  { name: 'MAHLE Original', url: 'mahle-original' },
  { name: 'AP Exhaust', url: 'ap-exhaust' },
  { name: 'MOOG Driveline Products', url: 'moog-driveline-products' },
  { name: 'Diamond Standard', url: 'diamond-standard' },
  { name: 'Deamotor', url: 'deamotor' },
  { name: 'Mevotech Supreme', url: 'mevotech-supreme' },
  { name: 'Sealed Power', url: 'sealed-power' },
  { name: 'Autolite Iridium XP', url: 'autolite-iridium-xp' },
  { name: 'Blue Streak', url: 'blue-streak' },
  { name: 'Platinum Plus', url: 'platinum-plus' },
  { name: 'Blue Streak Wire', url: 'blue-streak-wire' },
  { name: 'Davico Mfg', url: 'davico-mfg' },
  { name: 'Federal Parts', url: 'federal-parts' },
  { name: 'Graywerks', url: 'graywerks' },
  { name: 'Dayco', url: 'dayco' },
  { name: 'AISIN', url: 'aisin' },
  { name: 'Delphi', url: 'delphi' },
  { name: 'Rancho', url: 'rancho' },
  { name: 'KYB Shocks & Struts', url: 'kyb-shocks-and-struts' },
  { name: 'Rein', url: 'rein' },
  { name: 'PRO EFX', url: 'pro-efx' },
  { name: 'ANCO', url: 'anco' },
  { name: 'MOOG Hub Assemblies', url: 'moog-hub-assemblies' },
  { name: 'Eastern Catalytic', url: 'eastern-catalytic' },
  { name: 'ATP', url: 'atp' },
  { name: 'Beck/Arnley', url: 'beck-arnley' },
  { name: 'STOP BY BENDIX', url: 'stop-by-bendix' },
  { name: 'Akebono ProACT', url: 'akebono-proact' },
  { name: 'Dorman - Autograde', url: 'dorman-autograde' },
  { name: 'Goodmark', url: 'goodmark' },
  { name: 'Dorman - OE Solutions', url: 'dorman-oe-solutions' },
  { name: 'Driven by ATP', url: 'driven-by-atp' },
  { name: 'Bosal', url: 'bosal' },
  { name: 'Pentosin', url: 'pentosin' },
  { name: 'Champion Spark Plug', url: 'champion-spark-plug' },
  { name: 'Mevotech Duraflex', url: 'mevotech-duraflex' },
  { name: 'Bosch', url: 'bosch' },
  { name: 'Mevotech TTX', url: 'mevotech-ttx' },
  { name: 'Bando', url: 'bando' },
  { name: 'DENSO Auto Parts', url: 'denso-auto-parts' },
  { name: 'Cardone Select', url: 'cardone-select' },
  { name: 'Dorman - HELP', url: 'dorman-help' },
  { name: 'Speed Pro', url: 'speed-pro' },
  { name: 'Cardone Ultra', url: 'cardone-ultra' },
  { name: 'Fel-Pro', url: 'fel-pro' },
  { name: 'BENDIX FLEET METLOK', url: 'bendix-fleet-metlok' },
  { name: 'Contitech Products', url: 'contitech-products' },
  { name: 'Mevotech BXT', url: 'mevotech-bxt' },
  { name: 'BENDIX PREMIUM COPPER FREE', url: 'bendix-premium-copper-free' },
  { name: 'Airtex Fuel Pumps', url: 'airtex-fuel-pumps' },
  { name: 'Replace', url: 'replace' },
  { name: 'ATE', url: 'ate' },
  { name: 'Monroe Shocks & Struts', url: 'monroe-shocks-and-struts' },
  { name: 'ValueLine', url: 'valueline' },
  { name: 'Handy Pack', url: 'handy-pack' },
  { name: 'C-Tek', url: 'c-tek' },
  { name: 'SKF', url: 'skf' },
  { name: 'IPAP', url: 'ipap' },
  { name: 'PowerBond by Dayco', url: 'powerbond-by-dayco' },
  { name: 'TYC', url: 'tyc' },
  { name: 'Centric Parts', url: 'centric-parts' },
  { name: 'Platinum Pro', url: 'platinum-pro' },
  { name: 'BENDIX PREMIUM BRAKE SHOES', url: 'bendix-premium-brake-shoes' },
  { name: 'Ansa', url: 'ansa' },
  { name: 'Akebono Performance', url: 'akebono-performance' },
  { name: 'APDI', url: 'apdi' },
  { name: 'Replacement', url: 'replacement' },
  { name: 'Kool Vue', url: 'kool-vue' },
  { name: 'JC Whitney', url: 'jc-whitney' },
  { name: 'Beckarnley', url: 'beckarnley' },
];
export default brandList;
