const CategoriesList = [
  {
    name: 'Air and Fuel Delivery',
    url: 'air-and-fuel-delivery',
    imgsrc: `assets/images/Categories/Air_and_Fuel_Delivery.jpg`,
  },
  {
    name: 'Suspension',
    url: 'suspension',
    imgsrc: `assets/images/Categories/Suspension.jpg`,
    show: true,
  },
  {
    name: 'Electrical Lighting and Body',
    url: 'electrical-lighting-and-body',
    imgsrc: `assets/images/Categories/Electrical_Lighting_and_Body.jpg`,
    show: true,
  },
  {
    name: 'Exhaust',
    url: 'exhaust',
    imgsrc: `assets/images/Categories/Exhaust.jpg`,
    show: true,
  },
  {
    name: 'Brake',
    url: 'brake',
    imgsrc: `assets/images/Categories/Brake.jpg`,
    show: true,
  },
  {
    name: 'Tire and Wheel',
    url: 'tire-and-wheel',
    imgsrc: `assets/images/Categories/Tire_and_Wheel.jpg`,
    show: true,
  },
  {
    name: 'HVAC',
    url: 'hvac',
    imgsrc: `assets/images/Categories/HVAC.jpg`,
    show: true,
  },
  {
    name: 'Ignition',
    url: 'ignition',
    imgsrc: `assets/images/Categories/Ignition.jpg`,
    show: true,
  },
  {
    name: 'Engine',
    url: 'engine',
    imgsrc: `assets/images/Categories/Engine.jpg`,
    show: true,
  },
  {
    name: 'Steering',
    url: 'steering',
    imgsrc: `assets/images/Categories/Transmission.jpg`,
    show: false,
  },
  {
    name: 'Transmission',
    url: 'transmission',
    imgsrc: `assets/images/Categories/Transmission.jpg`,
    show: true,
  },
  {
    name: 'Entertainment and Telematics',
    url: 'entertainment-and-telematics',
    imgsrc: `assets/images/Categories/Wheel.jpg`,
    show: false,
  },
  {
    name: 'Air and Fuel Delivery',
    url: 'air-and-fuel-delivery',
    imgsrc: `assets/images/Categories/Air_and_Fuel_Delivery.jpg`,
    show: true,
  },
  {
    name: 'Electrical, Charging and Starting',
    url: 'electrical-charging-and-starting',
    imgsrc: `assets/images/Categories/Electrical_Charging_and_Starting.jpg`,
    show: true,
  },
  {
    name: 'Belts and Cooling',
    url: 'belts-and-cooling',
    imgsrc: `assets/images/Categories/belts_and_cooling.jpg`,
    show: true,
  },
  {
    name: 'Accessories and Fluids',
    url: 'accessories-and-fluids',
    imgsrc: `assets/images/Categories/accessories-and-fluids.jpg`,
    show: true,
  },
  {
    name: 'Hardware and Service Supplies',
    url: 'hardware-and-service-supplies',
    imgsrc: `assets/images/Categories/Wheel.jpg`,
    show: true,
  },
  {
    name: 'Emission Control',
    url: 'emission-control',
    imgsrc: `assets/images/Categories/Emission_Control.jpg`,
    show: true,
  },
  {
    name: 'Transfer Case',
    url: 'transfer-case',
    imgsrc: `assets/images/Categories/Wheel.jpg`,
    show: true,
  },
  {
    name: 'Suspension',
    url: 'suspension',
    imgsrc: `assets/images/Categories/Suspension.jpg`,
    show: true,
  },
  {
    name: 'Driveline and Axles',
    url: 'driveline-and-axles',
    imgsrc: `assets/images/Categories/Wheel.jpg`,
    show: true,
  },
  {
    name: 'Wiper and Washer',
    url: 'wiper-and-washer',
    imgsrc: `assets/images/Categories/Wheel.jpg`,
    show: true,
  },
  {
    name: 'Tools and Equipment',
    url: 'tools-and-equipment',
    imgsrc: `assets/images/Categories/Wheel.jpg`,
    show: true,
  },
];
export default CategoriesList;
